apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w805ph28u-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/w805ph28u-java-quarkus-gitops